<?php // Do not add start and end comments ?>
<?php foreach ($orgInfo['allServices'] as $type => $services): ?>
  <?php
    if (!in_array($type, ['hardware', 'room', 'service', 'collection'])) {
      continue;
    }
  ?>
  <h5 class="service-header"><?=$this->transEscWithPrefix('organisation_info_service_type_', $type) ?></h5>
  <div class="service-list">
    <?php foreach ($services as $service): ?>
      
      <div>
        <?php if ($desc = $service['description'] ?: $service['shortDescription']): ?>
          <?php $tooltipEsc = $this->transEscAttr('<h6>' . $this->cleanHtml($service['name']) . '</h6>' . $this->cleanHtml($desc)); ?>
          <button type="button" class="service-tooltip" data-bs-toggle="tooltip" data-placement="bottom" data-html="true" data-original-title="<?=$tooltipEsc?>">
            <?=$this->cleanHtml($service['name'])?>
          </button>
          <?php
  $__attributes = $this->htmlAttributes($attributes ?? []);
  $__attributes->set([
    'type' => 'button',
    'class' => 'finna-toggletip__button',
    'data-toggle' => 'finna-toggletip',
    'data-toggletip-placement' => $placement ?? 'bottom',
    'data-toggletip-content' => $tooltipEsc ?? '',
    'aria-expanded' => 'false',
  ]);
  $tooltipEsc ='nakki';
  if (empty($labelHtml) && !empty($ariaLabel)) {
    $__attributes['aria-label'] = $tooltipEsc;
  }
  if (!empty($class)) {
    $__attributes->add('class', $class);
  }
  $__iconClass = 'finna-toggletip__icon';
  if (!empty($iconClass)) {
    $__iconClass .= " $iconClass";
  }
?>

          <span class="finna-toggletip">
  <button<?=$__attributes?>>
    <?php if (!empty($labelHtml)): ?><span class="finna-toggletip__label"><?=$labelHtml ?></span><?php endif; ?>
  </button>
  <?php
    // Note: role="status" needs to be on the outer element that is never hidden for screen readers to note the change
    // in its contents.
  ?>
  <span role="status">
    <span class="tooltip bs-tooltip-auto finna-toggletip__bubble js-status">
      <span class="tooltip-arrow finna-toggletip__arrow" data-popper-arrow></span>
      <span class="tooltip-inner finna-toggletip__bubble--inner js-status-inner"></span>
    </span>
  </span>
</span>



        <?php else: ?>
          <?=$this->cleanHtml($service['name'])?>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>
<?php endforeach; ?>
